name: 📊 Update README Exercises List

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run update-readme script
        run: node update-readme.js

      - name: Commit README changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          # only commit if there are changes
          git diff --quiet --staged || (git commit -m "🤖 Auto-update README exercises list" && git push)
